#省略窗口切换，测试更流畅
#此文件名后缀必须为.http
GET http://localhost:8880/hello
#Accept: application/json
#一个http可以写多个测试脚本

#单元测试
> {%
   /*client.test("test-hello", function() {
   client.log("测试/hello接口");
   client.log(resp.body);
   client.log(JSON.stringify(resp.body)); // 虽然idea没有提示JSON，但是可以用
   client.assert(resp.status === 200, "返回码不是200");
   client.assert(resp.body === "Hello World!Hello", "结果验证失败");
 });*/
 %}

###

POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###

GET http://localhost:8880/test/list

###